refactor(wip): jumpy-stain

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,38 +1,43 @@
 ---
-name: test
+name: go-tests
 on:
   pull_request:
-  # push:
-  # branches:
-  #   - main
-  # tags:
-  #   - v*
+  push:
+    tags:
+      - v*
   workflow_dispatch:
-  workflow_call:
-permissions:
-  contents: read
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
-env:
-  AQUA_LOG_LEVEL: debug
-  AQUA_OPTS: ''
+defaults:
+  run:
+    shell: bash
+    working-directory: .
 jobs:
   test:
     runs-on: ubuntu-latest
-    timeout-minutes: 5
+    timeout-minutes: 10
     steps:
       - uses: actions/checkout@v3
-      - name: aqua-install
-        run: |
-          curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -i /usr/local/bin/aqua
-          echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
-          [[ -e "${AQUA_CONFIG}" ]] && echo "✅ AQUA_CONFIG: ${AQUA_CONFIG} exists" ||  echo "::error ❗ unable to validate the target file: ${AQUA_CONFIG} exists"
-          aqua install # --only-link
+      - uses: aquaproj/aqua-installer@v1.1.2
+        with:
+          aqua_version: v1.20.2
+          enable_aqua_install: true
+          # aqua_opts: ""
         env:
-          AQUA_CONFIG: aqua.ci.yaml
+          # AQUA_CONFIG: '${{ github.workspace }}/aqua.yaml'
           AQUA_LOG_LEVEL: debug
-          AQUA_OPTS: ''
+          AQUA_OPTS:
+            ''
+            # working_directory: "${{ github.workspace }}"
+
+      # - name: aqua-install
+      #   run: |
+      #     curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -i /usr/local/bin/aqua
+      #     # echo "$HOME/.local/share/aquaproj-aqua/bin" >> $GITHUB_PATH
+      #     # [[ -e "${AQUA_CONFIG}" ]] && echo "✅ AQUA_CONFIG: ${AQUA_CONFIG} exists" ||  echo "::error ❗ unable to validate the target file: ${AQUA_CONFIG} exists"
+      #     ls -lla "${{ github.workspace }}"
+      #   env:
+      #     AQUA_CONFIG: '${{ github.workspace }}/aqua.yaml'
+      #     AQUA_LOG_LEVEL: debug
+      #     AQUA_OPTS: ""
       - name: env-config-go
         run: |
           echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
@@ -48,30 +53,31 @@ jobs:
 
       - name: mage-init
         run: |
-          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:${PATH}"
+          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua:${PATH}"
           export PATH="$(go env GOPATH)/bin:${PATH}"
+          # aqua install # --only-link
           mage init
-
-      - name: mage-gotestsum
+      - name: mage-testsum
         run: |
-          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:${PATH}"
+          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua:${PATH}"
           export PATH="$(go env GOPATH)/bin:${PATH}"
-
           mage go:testsum ./...
         env:
           # Race conditions will be hit due to the cli driven tasks and binaries being called.
           GOTEST_DISABLE_RACE: 1
-      - name: Upload coverage reports to Codecov
-        run: |
-          # curl -Os https://uploader.codecov.io/latest/linux/codecov
-          # chmod +x codecov
-          # ./codecov -t ${CODECOV_TOKEN}
-          # improved codecov with signature verification
-          curl https://uploader.codecov.io/verification.gpg | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
-          curl -Os https://uploader.codecov.io/latest/linux/codecov
-          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
-          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
-          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
-          shasum -a 256 -c codecov.SHA256SUM
-          chmod +x codecov
-          ./codecov
+          GOTESTS: 'slow'
+
+          GOTEST_FLAGS: '--tags=integration'
+
+      # Must be public for this to work
+      # - name: Upload coverage reports to Codecov
+      #   run: |
+      #     # improved codecov with signature verification
+      #     curl https://uploader.codecov.io/verification.gpg | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
+      #     curl -Os https://uploader.codecov.io/latest/linux/codecov
+      #     curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
+      #     curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
+      #     gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
+      #     shasum -a 256 -c codecov.SHA256SUM
+      #     chmod +x codecov
+      #     ./codecov -t ${{ secrets.CODECOV_TOKEN }}
